# Generated by Django 3.0.8 on 2020-08-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('offer_value', models.IntegerField(max_length=2)),
                ('product_catogary', models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN'), ('kids', 'KIDS'), ('other', 'OTHER')], default='men', max_length=15)),
                ('catogary_type', models.CharField(choices=[('t-shirt', 'T-shirt'), ('shirt', 'shirt'), ('Trouser', 'Trouser'), ('jeans', 'Jeans'), ('tops', 'Tops'), ('leggings', 'Leggings'), ('sarees', 'Sarees'), ('kurta', 'Kurta'), ('mask', 'Mask')], default='t-shirt', max_length=15)),
            ],
        ),
    ]
